modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"
issueTrackerURL = "https://github.com/Ocelot5836/beyond/issues"
[[mods]]
modId = "beyond"
version = "${version}"
displayName = "Beyond"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile = "examplemod.png"
credits = "CoffeeCatRailway for making the satellite model and texture. BlueBarracuda for composing the music for the moon."
authors = "Ocelot"
description = "Pretty cool space exploration mod broh."
[[dependencies.beyond]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.beyond]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
